### ISSUE TITLE
Make MenuProvider method implementations optional

### ISSUE THREAD

**Issue by olback** [talklittle/nautilus-extension-rs#8]
I think that `get_file_items` and `get_background_items` should have default implementations. This allows users to not implement unnecessary code.

Thoughts?

**Comment by talklittle** [comment]
That is a good idea.

So for example returning `Option<Vec<MenuItem>>` (Some/None) at https://github.com/talklittle/nautilus-extension-rs/blob/a747fb0c4b8ac222d1a3e816043dae3491fe3d66/nautilus-extension/src/menu_provider.rs#L195-L199

**Comment by olback** [comment]
My idea was to change this https://github.com/talklittle/nautilus-extension-rs/blob/a747fb0c4b8ac222d1a3e816043dae3491fe3d66/nautilus-extension/src/menu_provider.rs#L16-L19

to something like this:

```rust
pub trait MenuProvider : Send + Sync {

    fn get_file_items(&self, window: *mut GtkWidget, files: &Vec<FileInfo>) -> Vec<MenuItem> {
        Vec::new()
    }

    fn get_background_items(&self, window: *mut GtkWidget, current_folder: &FileInfo) -> Vec<MenuItem> {
        Vec::new()
    }

}
```

This would allow you to implement `get_file_items` without `get_background_items` and the other way arround.

**Comment by talklittle** [comment]
That's better. :+1:
